# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ankit Muchhala
email: muchhalaankit@gmail.com
description: Front end developer and graphic designer. Foodie. F1 and Football enthusiast. Lot of Fs! Oh! I am also a Freelancer. Get in touch for work!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ankit_muchhala
github_username:  ankit-m

# Build settings
markdown: kramdown
